### ISSUE TITLE
some deployments cannot migrate due to violated not-null constraints on various migrations

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#176]
We've encountered some inconsistent state on one Beiwe deployment that occur during migration.  fixes appear to be easy, but the stack traces and psychopg errors are almost unreadable.

stack trace here is an example of the issue, proximate cause of bad statte is unknown, error itself is clear... ish.

```
[2020-11-20T22:49:30.398Z] INFO  [10000] - [Application update ################ /AppDeployStage0/EbExtensionPostBuild/Infra-EmbeddedPostBuild/postbuild_0_beiwe_application/Command 02_migrate] : 

Activity execution failed, because: Operations to perform:
  Apply all migrations: database
  Running migrations:
  Applying database.0032_custom...Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  return self.cursor.execute(sql, params)
  psycopg2.errors.NotNullViolation: null value in column "archive_end" violates not-null constraint
  DETAIL:  Failing row contains (51, f, [], image_survey, {"always_available": false}, 2020-11-20 22:49:30.226992+00, null, null, 1, 2020-11-20 22:49:30.236963+00, 2020-11-20 22:49:30.236994+00).
  
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
  File "manage.py", line 10, in <module>
  execute_from_command_line(sys.argv)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
  utility.execute()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
  self.execute(*args, **cmd_options)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
  output = self.handle(*args, **options)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
  res = handle_func(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
  fake_initial=fake_initial,
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
  state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
  state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
  state = migration.apply(state, schema_editor)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
  operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
  self.code(from_state.apps, schema_editor)
  File "/opt/python/bundle/3/app/database/migrations/0032_custom.py", line 12, in backfill_missing_survey_archives
  survey.save()
  File "/opt/python/bundle/3/app/database/survey_models.py", line 165, in save
  self.archive()
  File "/opt/python/bundle/3/app/database/survey_models.py", line 199, in archive
  archive_start=archive_start,
  File "/opt/python/bundle/3/app/database/common_models.py", line 129, in save
  super().save(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
  force_update=force_update, update_fields=update_fields)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
  force_update, using, update_fields,
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
  result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
  using=using, raw=raw)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
  return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
  return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
  cursor.execute(sql, params)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
  return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
  return executor(sql, params, many, context)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  return self.cursor.execute(sql, params)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
  raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
  return self.cursor.execute(sql, params)
  django.db.utils.IntegrityError: null value in column "archive_end" violates not-null constraint
  DETAIL:  Failing row contains (51, f, [], image_survey, {"always_available": false}, 2020-11-20 22:49:30.226992+00, null, null, 1, 2020-11-20 22:49:30.236963+00, 2020-11-20 22:49:30.236994+00).
  
   (ElasticBeanstalk::ExternalInvocationError)


```

**Comment by biblicabeebli** [comment]
the above is not from committed code, it is from debugging code, your code probably will not match some line numbers.  This is the second error of this type encountered.

Fixes generally involve simplifying the code, get_or_create is specifically cranky so we might need to separate database calls.

**Comment by biblicabeebli** [comment]
resolved, pushed to master.
