### ISSUE TITLE
Changes to openssh(?) have broken ssh connection when deploying manager/worker server

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#182]
The title is a guess at what is going on.

You will see an error like this if deploying from Ubuntu 20.10, in which you also receive messages about RSA ssh keys being retired (`load pubkey "blah/blah/blah.pem": invalid format`).

```
ERROR paramiko.transport: Exception: Error reading SSH protocol banner
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/python_env/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR paramiko.transport:     buf = self.packetizer.readline(timeout)
ERROR paramiko.transport:   File "/python_env/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
ERROR paramiko.transport:     buf += self._read_timeout(timeout)
ERROR paramiko.transport:   File "/python_env/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR paramiko.transport:     raise EOFError()
ERROR paramiko.transport: EOFError
ERROR paramiko.transport: 
ERROR paramiko.transport: During handling of the above exception, another exception occurred:
ERROR paramiko.transport: 
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/python_env/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
ERROR paramiko.transport:     self._check_banner()
ERROR paramiko.transport:   File "/python_env/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
ERROR paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERROR paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR paramiko.transport: 
ERROR cluster-management: Encountered error of type NetworkError with error message "Error reading SSH protocol banner"
Retrying with attempt 95.

```

**Comment by biblicabeebli** [comment]
Ha, okay, false alarm... key was missing, paramiko is just... weird, apparently...
