### ISSUE TITLE
Updated to latest master, UI getting 500 errors due to AttributeError in timezone_dropdown.py

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#185]
In an effort to see if the latest code fixes this bug/issue:

```
Error: Incorrect padding
  File "libs/security.py", line 71, in decode_base64
    return base64.urlsafe_b64decode(data)
  File "python3.6/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
Base64LengthException: Data provided had invalid length 523 after padding was removed.
  File "flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 39, in reraise
    raise value
  File "flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "libs/http_utils.py", line 43, in provide_os_determination_and_call
    return some_function(*args, **kwargs)
  File "authentication/user_authentication.py", line 43, in authenticate_and_call
    return some_function(*args, **kwargs)
  File "api/mobile_api.py", line 100, in upload
    uploaded_file = decrypt_device_file(patient_id, uploaded_file, client_private_key, user)
  File "libs/encryption.py", line 136, in decrypt_device_file
    decoded_key = decode_base64(file_data[0])
  File "libs/security.py", line 76, in decode_base64
    raise Base64LengthException(f"Data provided had invalid length {length} after padding was removed.")
```
... which comes from a new participant on a Google Pixel 3 w/ Android 11, it seems, 

I pulled latest master and re-deployed the processing manager.   Subsequently, the web UI returns 500s and the web server error log indicates the following issue:

```
AttributeError: 'NoneType' object has no attribute '_ttinfo_std'
mod_wsgi (pid=20087): Target WSGI script '/opt/python/current/app/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=20087): Exception occurred processing WSGI script '/opt/python/current/app/wsgi.py'.
Traceback (most recent call last):
  File "/opt/python/current/app/wsgi.py", line 11, in <module>
    from app import app as application
  File "/opt/python/current/app/app.py", line 9, in <module>
    from api import (admin_api, copy_study_api, dashboard_api, data_access_api, mobile_api,
  File "/opt/python/current/app/api/admin_api.py", line 14, in <module>
    from libs.timezone_dropdown import ALL_TIMEZONES
  File "/opt/python/current/app/libs/timezone_dropdown.py", line 73, in <module>
    ALL_TIMEZONES_DROPDOWN = flatten_time_zones(build_dictionary_of_timezones())
  File "/opt/python/current/app/libs/timezone_dropdown.py", line 39, in build_dictionary_of_timezones
    utc_offset: timedelta = tz_info._ttinfo_std.delta
AttributeError: 'NoneType' object has no attribute '_ttinfo_std'
```

I haven't yet had time to dig through the code myself to troubleshoot this, but any quick advice would be much appreciated.

**Comment by biblicabeebli** [comment]
Hm, well that's odd. That's part of the code to populate a list of time zones, which I tested pretty thoroughly and am not having an issue with on the Onnela lab deployments.

Also, that code executes at python-load-time, so I don't know how you were even able to deploy successfully, that just doesn't make sense.

I'm going to remove the dynamic generation of the list and replace it with a hardcoded one, expect a commit in the next 15 minutes on master.

**Comment by biblicabeebli** [comment]
I've hardcoded the object instead of generating it.
I don't know why your server instance is... missing system-level timezone information?  I guess we just can't have nice things.

Let me know if you have any further issues, please close this issue if it is resolved.

**Comment by jakeczyz** [comment]
Thanks Eli.  That resolved the issue.

FWIW, here's the bad one on my Elastic Beanstalk machine (Amazon Linux AMI 2018.03)

```
>>> for _, timezones_by_country in pytz.country_timezones.items():
...   tzs.extend(timezones_by_country)
>>> len(tzs)
425
>>> okays = []
>>> for zone_name in tzs:
...   tz_info = tz.gettz(zone_name)
...   try:
...     utc_offset =  tz_info._ttinfo_std.delta
...   except:
...      print('failed on: %s' % zone_name)
...   else:
...      okays.append(zone_name)
...
failed on: America/Nuuk
>>> len(okays)
424
```

**Comment by biblicabeebli** [comment]
Okay, thanks, and weird.

I do recommend updating the "platform version" id it is old.  I've forgotten if version upgrades are enabled by default, if not do enable that for piece of mind.
