### ISSUE TITLE
403 Forbidden Error when attempting to download data

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#203]
Hello! We started getting a 403 Forbidden error when attempting to download data.  I can replicate this via multiple user accounts.  

The only errors I'm seeing in Sentry and the httpd error log are 404s and a crash due to missing favicon.ico, which I'm not sure is related (unless that somehow leads to the 403...)

```
[2021-06-21 17:10:25,213] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/opt/python/current/app/app.py", line 82, in e404
    return render_template("404.html", is_logged_in=is_logged_in()), 404
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "frontend/templates/404.html", line 1, in top-level template code
    {% extends 'base.html'%}
  File "frontend/templates/base.html", line 45, in top-level template code
    {% block navbar %}
  File "frontend/templates/404.html", line 8, in block "navbar"
    {{ super() }}
  File "frontend/templates/base.html", line 46, in block "navbar"
    {% include 'navbar.html' %}
  File "frontend/templates/navbar.html", line 1, in top-level template code
    <script>navBarStudies = {{ allowed_studies|tojson }}</script>
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/json/__init__.py", line 376, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/json/__init__.py", line 290, in htmlsafe_dumps
    dumps(obj, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable
```

Any suggestions on where to look next?

**Comment by biblicabeebli** [comment]
This stacktrace is a rendering error relating to weird jain in the navbar dropdown of studies

**Comment by jakeczyz** [comment]
Thanks. I created a new issue for the 404.  I think the 403 may be UI/UX issue.  I recently deleted two users, one of whom may have been the one who created data access credentials for the team.  After this, the credentials no longer worked. In the "Manage Credentials" page, there is a way to reset two different kinds of credentials, but it's not super clear that they differ or which is which.  (Also, clicking reset at the bottom shows the new creds at the top of the page, but the page does not scroll up; so, it's not clear to scroll up to copy them. I recommend a popup.)

**Comment by jakeczyz** [comment]
Confirmed that resetting the credentials via the lower button "Reset Data Download API Access Credentials" (as opposed to  "Generate New API Key") produces valid keys.   I'm closing, but I still would suggest improving the UX on this page to avoid future confusion.

**Comment by shuvammishra** [comment]
> Confirmed that resetting the credentials via the lower button "Reset Data Download API Access Credentials" (as opposed to "Generate New API Key") produces valid keys. I'm closing, but I still would suggest improving the UX on this page to avoid future confusion.

Ran into the same issue. This worked for me. Thanks!
