### ISSUE TITLE
Troubleshooting ModuleNotFoundError: No module named 'forest'

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#209]
This is a troubleshooting issue in case you updated the data processing server in a cluster deployment to the current version of `master` and then your Celery tasks crashed every time you ran them.  Symptoms:
* No notifications being sent
* New data not being processed/available for download
* The following stack trace present in `/var/mail/ubuntu` from running cron:
    ```
    Traceback (most recent call last):
      File "services/cron.py", line 12, in <module>
        from services.celery_forest import create_forest_celery_tasks
      File "/home/ubuntu/beiwe-backend/services/celery_forest.py", line 11, in <module>
        from forest.jasmine.traj2stats import gps_stats_main
    ModuleNotFoundError: No module named 'forest'
    ```

**Comment by zagorsky** [comment]
To fix it, here's what you need to do on the data processing server:
1. Run `pip install -r requirements_data_processing.txt`.  This should install `forest` from GitHub.
2. Copy the file `/beiwe-backend/cluster_management/pushed_files/install_celery_worker.sh` into the server's `~/` directory (this file already exists in the server's `~/` directory, but you need to update it
3. Run `sudo processing-restart`

**Comment by zagorsky** [comment]
Now documented here: https://github.com/onnela-lab/beiwe-backend/wiki/Forest-setup
