### ISSUE TITLE
purge participant data - QuerySet error

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-backend#257]
Hi, i am trying to purge participant data from my study using the purge_participant_data.py script on my elastic beanstalk server.  Suggestions?

```
[ec2-user@ip-xxx scripts]$ python purge_participant_data.py purgees.json

7umfmb98 -- October 15 2021

I hereby confirm that I want to irreparably delete all data for the above users starting on the day listed. (y/n)
y

removing ChunkRegistry data for 7umfmb98...
/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField ChunkRegistry.time_bin received a naive datetime (2021-10-15 00:00:00) while time zone support is active.
  RuntimeWarning)
Traceback (most recent call last):
  File "purge_participant_data.py", line 202, in <module>
    delete_chunk_registries(setup_data)
  File "purge_participant_data.py", line 119, in delete_chunk_registries
    ChunkRegistry.objects.filter(participant=participant, time_bin__gte=date).delete()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/deletion.py", line 294, in delete
    count = qs._raw_delete(using=self.using)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 725, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1129, in execute_sql
    sql, params = self.as_sql()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1400, in as_sql
    where, params = self.compile(self.query.where)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 130, in as_sql
    return super().as_sql(compiler, connection)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 163, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 257, in process_rhs
    'The QuerySet value for an exact lookup must be limited to '
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
```

**Comment by biblicabeebli** [comment]
This method of participant purge has been removed.

There is now a "more official" (e.g. maintained) mechanism that runs in the background as a processing server task, but _it does not yet have a front end hooked up to it_.  I'm closing this issue, if anyone needs this feature and there isn't an obvious UI for it on the participant page (of a server running a future version of the main branch) please post a new issue requesting we prioritize it.
