### ISSUE TITLE
Large error reports fail to send to sentry

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#260]
This error was encountered inside a decryption key error, the error failed to be reported or stashed.
This is probably exactly what is stated, the error has associated assets that are larger than sentry likes, but we don't currently have a way to resolve that.

plausibly related issue: https://github.com/onnela-lab/beiwe-backend/issues/186

```
Sentry responded with an error: HTTP Error 413: Request Entity Too Large (url: https://sentry.io/api/*****/store/)
Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
File "/opt/python/run/venv/local/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large
```

**Comment by biblicabeebli** [comment]
probably blocked by https://github.com/onnela-lab/beiwe-backend/issues/261

**Comment by biblicabeebli** [comment]
closing as this issue serves no purpose, also cronutils is being updated to use the new sentry library
