### ISSUE TITLE
The instance profile associated with the environment has no role

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#32]
Error report from Tim:

> We started over and hit an issue at `launch_script.py -create-environment`. I'll paste the log output below.
> 
> This step of the deployment process created an IAM role beiwetest-elasticbeanstalk-service-role with attached policies AWSElasticBeanstalkEnhancedHealth and AWSElasticBeanstalkService. It also created the RDS instance and corresponding VPC Security Groups and bucket. 
> 
> However creating the Elastic Beanstalk environment/Application failed with the following error (from Elastic Beanstalk console):
>
> `The instance profile beiwetest-elasticbeanstalk-instance-profile associated with the environment has no role. Please attach a role to the instance profile.`
> 
> Unfortunately the application is automatically Terminated at this point and scheduled for deletion. Any hints/suggestions/insights would certainly help move things along.
> 
> Here's that launch_script.py log output I mentioned above:
> 

```
$ python launch_script.py -create-environment

Please enter the name of the environment for which you have filled out the required settings:
nrg-beiwe

[trimmed]
INFO cluster-management: database credentials have been written to /.../beiwe-backend/django-merge/cluster_management/environment_configuration/nrg-beiwe_database_credentials.json
INFO cluster-management: Creating RDS Postgres database named nrg-beiwe-database
INFO cluster-management: 2018-03-15 15:44:07: RDS instance status is creating, waiting until status is "Ready"
INFO cluster-management: 2018-03-15 15:44:07: RDS instance status is creating, waiting until status is "Ready"
[trimmed]
INFO cluster-management: Database status is no longer 'creating', it is 'available'
INFO cluster-management: checking availability of bucket name 'beiwe-data-nrg-beiwe-...'
INFO cluster-management: eb service role not found, creating...
INFO cluster-management: creating a new Elastic Beanstalk environment named nrg-beiwe... this will take a while.
ERROR cluster-management: 
***********************************************************
Warning: encountered multiple Python 2.7 Elastic Beanstalk environment platforms.
Beiwe did its best to automatically determine which environment to use.
After deployment finishes, determine whether there is a platform upgrade you can
apply for this cluster.
***********************************************************
INFO cluster-management: 2018-03-15 14:08:05: Elastic Beanstalk status is "Launching", waiting until status is "Ready"
INFO cluster-management: 2018-03-15 14:08:10: Elastic Beanstalk status is "Launching", waiting until status is "Ready"
[trimmed]
ERROR cluster-management: environment deployment failed:
{u'ApplicationName': 'beiwe-application', u'EnvironmentName': 'nrg-beiwe', u'Status': 'Terminated', u'Description': 'elastic beanstalk beiwe cluster', u'EnvironmentLinks': [], u'PlatformArn': 'arn:aws:elasticbeanstalk:us-east-1::platform/Python 2.7 running on 64bit Amazon Linux/2.6.5', u'SolutionStackName': '64bit Amazon Linux 2017.09 v2.6.5 running Python 2.7', u'EnvironmentId': 'e-...', u'Health': 'Grey', u'AbortableOperationInProgress': False, u'Tier': {u'Version': '1.0', u'Type': 'Standard', u'Name': 'WebServer'}, u'HealthStatus': 'Unknown', u'DateUpdated': datetime.datetime(2018, 3, 15, 18, 11, 18, 967000, tzinfo=tzutc()), u'DateCreated': datetime.datetime(2018, 3, 15, 18, 8, 5, 302000, tzinfo=tzutc()), u'EnvironmentArn': 'arn:aws:elasticbeanstalk:us-east-1:...:environment/beiwe-application/nrg-beiwe'}
Traceback (most recent call last):
  File "launch_script.py", line 521, in <module>
    do_create_environment()
  File "launch_script.py", line 314, in do_create_environment
    create_eb_environment(name)
  File "/.../beiwe-backend/django-merge/cluster_management/deployment_helpers/aws/elastic_beanstalk.py", line 297, in create_eb_environment
    raise EnvironmentDeploymentFailure(msg)
deployment_helpers.aws.iam.EnvironmentDeploymentFailure: environment deployment failed:
{u'ApplicationName': 'beiwe-application', u'EnvironmentName': 'nrg-beiwe', u'Status': 'Terminated', u'Description': 'elastic beanstalk beiwe cluster', u'EnvironmentLinks': [], u'PlatformArn': 'arn:aws:elasticbeanstalk:us-east-1::platform/Python 2.7 running on 64bit Amazon Linux/2.6.5', u'SolutionStackName': '64bit Amazon Linux 2017.09 v2.6.5 running Python 2.7', u'EnvironmentId': 'e-...', u'Health': 'Grey', u'AbortableOperationInProgress': False, u'Tier': {u'Version': '1.0', u'Type': 'Standard', u'Name': 'WebServer'}, u'HealthStatus': 'Unknown', u'DateUpdated': datetime.datetime(2018, 3, 15, 18, 11, 18, 967000, tzinfo=tzutc()), u'DateCreated': datetime.datetime(2018, 3, 15, 18, 8, 5, 302000, tzinfo=tzutc()), u'EnvironmentArn': 'arn:aws:elasticbeanstalk:us-east-1:...:environment/beiwe-application/nrg-beiwe'}
```

**Comment by biblicabeebli** [comment]
This is the result of incomplete cleanup of prior state, specifically the instance profile role "beiwetest-elasticbeanstalk-instance-profile-role" was deleted out from under the instance profile "beiwetest-elasticbeanstalk-instance-profile".

Fixing this would require an obnoxious and error-prone rewrite of deployment_helpers/aws/elastic_beanstalk.py:get_or_create_eb_instance_profile.  The solution is to have a better way of clearing out all the IAM components so that users don't have inconsistent (and unmaintainable) IAM state to manage.

In development I built a helper tool to assist my own sanity in resetting everything, I have surfaced this in the launch script as "-purge_instance_profiles".  Its on the django-merge branch (soon to be merged into django).  Read the help text before running this command.

comment on those names:
Yeah, they shouldn't be named "beiwetest..." This is a problem because it is hardcoded in deployment_helpers/constants.py, and if it changes it is going to break all existing deployments.  I am not positioned to know what deployments exist and/or what state of functionality they are in, and I am not going too fix that.
