### ISSUE TITLE
Encountering Error after "eb deploy"

### ISSUE THREAD

**Issue by Ilurusheshasai** [onnela-lab/beiwe-backend#381]
Hi Everyone I am facing this error when I try to run eb deploy. What could be the potential reason?

[ec2-user@ip-*-*-*-* beiwe-backend]$ eb deploy 
Creating application version archive "app-64b79-240419_004915795045". 
Uploading beiwe-application/app-64b79-240419_004915795045.zip to S3. This may take a while. 
Upload Complete. 

2024-04-19 00:49:17    INFO    Environment update is starting. 
2024-04-19 00:49:47    INFO    Deploying new version to instance(s). 
2024-04-19 00:50:24    ERROR   Instance deployment failed to install application dependencies. The deployment failed. 
2024-04-19 00:50:24    ERROR   Instance deployment failed. For details, see 'eb-engine.log'. 
2024-04-19 00:50:27    ERROR   [Instance: i-067*******] Command failed on instance. Return code: 1 Output: Engine execution has encountered an error.. 
2024-04-19 00:50:27    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1]. 
2024-04-19 00:50:27    ERROR   Unsuccessful command execution on instance id(s) 'i-067aaa0229a0c140f'. Aborting the operation. 
2024-04-19 00:50:27    ERROR   Failed to deploy application. 

ERROR: ServiceError - Failed to deploy application.

**Comment by Ilurusheshasai** [comment]
Also faced issues while running python launch_script.py -create-manager

WARNING cluster-management: For technical reasons we need to compile python. This will take some time. 
[3.141.15.242] run: /home/ubuntu/.pyenv/bin/pyenv install -v 3.8.13 >> /home/ubuntu/server_setup.log 
[3.141.15.242] out: Downloading Python-3.8.13.tar.xz... 
[3.141.15.242] out: -> https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tar.xz 
[3.141.15.242] out: Installing Python-3.8.13... 
[3.141.15.242] out: Installed Python-3.8.13 to /home/ubuntu/.pyenv/versions/3.8.13 
[3.141.15.242] out: 
[3.141.15.242] run: /home/ubuntu/.pyenv/bin/pyenv virtualenv 3.8.13 beiwe >> /home/ubuntu/server_setup.log 
[3.141.15.242] run: /home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install --upgrade pip setuptools wheel >> /home/ubuntu/server_setup.log 
[3.141.15.242] run: /home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements.txt >> /home/ubuntu/server_setup.log 
[3.141.15.242] out:   Running command git clone --filter=blob:none --quiet '[https://****@github.com/onnela-lab/forest](mailto:https://****@github.com/onnela-lab/forest)' /tmp/pip-install-uma012xf/forest_0dccdfea3e5d4c618c6542295f6fb5ee 
[3.141.15.242] out:   Running command git rev-parse -q --verify 'sha^1c0e7bcc9bed574b0392db7004921c51a440b4e0' 
[3.141.15.242] out:   Running command git fetch -q '[https://****@github.com/onnela-lab/forest](mailto:https://****@github.com/onnela-lab/forest)' 1c0e7bcc9bed574b0392db7004921c51a440b4e0 
[3.141.15.242] out:   Running command git checkout -q 1c0e7bcc9bed574b0392db7004921c51a440b4e0 
[3.141.15.242] out: 
[3.141.15.242] run: /home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements_data_processing.txt >> /home/ubuntu/server_setup.log 
[3.141.15.242] out: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/ubuntu/beiwe-backend/requirements_data_processing.txt' 
[3.141.15.242] out: 

Fatal error: run() received nonzero return code 1 while executing! 

Requested: /home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements_data_processing.txt >> /home/ubuntu/server_setup.log 
Executed: /bin/bash -l -c "/home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements_data_processing.txt >> /home/ubuntu/server_setup.log" 

Aborting. 

Traceback (most recent call last): 
  File "launch_script.py", line 643, in <module> 
    do_create_manager() 
  File "launch_script.py", line 478, in do_create_manager 
    setup_python() 
  File "launch_script.py", line 141, in setup_python 
    run(f'{python} -m pip install -r {REMOTE_HOME_DIR}/beiwe-backend/requirements_data_processing.txt >> {LOG_FILE}') 
  File "/home/ec2-user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/fabric/network.py", line 692, in host_prompting_wrapper 
    return func(*args, **kwargs) 
  File "/home/ec2-user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/fabric/operations.py", line 1092, in run 
    return _run_command( 
  File "/home/ec2-user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/fabric/operations.py", line 959, in _run_command 
    error(message=msg, stdout=out, stderr=err) 
  File "/home/ec2-user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/fabric/utils.py", line 359, in error 
    return func(message) 
  File "/home/ec2-user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/fabric/utils.py", line 55, in abort 
    raise env.abort_exception(msg) 
__main__.FabricExecutionError: run() received nonzero return code 1 while executing! 

Requested: /home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements_data_processing.txt >> /home/ubuntu/server_setup.log 

Executed: /bin/bash -l -c "/home/ubuntu/.pyenv/versions/beiwe/bin/python -m pip install -r /home/ubuntu/beiwe-backend/requirements_data_processing.txt >> /home/ubuntu/server_setup.log"

**Comment by biblicabeebli** [comment]
This should be resolved by updating the codebase.  There was a brief period where there was still some code referencing the requirements_data_processing.txt due to a mistake I made pushing that out too early.

 Just pull the main branch locally.
