### ISSUE TITLE
BadServerConfigurationError error while deploying

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-backend#41]
Hi, I'm getting the following error while deploying from the master branch

> $ eb deploy

```
> ..........
> INFO: Uploading archive to s3 location: beiwe-application/app-0629-180529_163856.zip
> Uploading beiwe-application/app-0629-180529_163856.zip to S3. This may take a while.
> Upload Complete.
> INFO: Creating AppVersion app-0629-180529_163856
> INFO: Environment update is starting.                               
> INFO: Deploying new version to instance(s).                         
> ERROR: [Instance: i-00cc6afd730575f7d] Command failed on instance. Return code: 1 Output: (TRUNCATED)...hon/bundle/3/app/config/__init__.py", line 75, in <module>
> raise BadServerConfigurationError("\n" + "\n".join(errors))
> config.BadServerConfigurationError:
> AWS_ACCESS_KEY_ID was not provided with a value.
> AWS_SECRET_ACCESS_KEY was not provided with a value. 
> container_command 04_migrate in .ebextensions/01.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
> INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
> ERROR: Unsuccessful command execution on instance id(s) 'i-00cc6afd730575f7d'. Aborting the operation.
> ERROR: Failed to deploy application.                                
>                                                                       
> INFO: Traceback (most recent call last):
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/core/ebrun.py", line 41, in run_app
>     app.run()
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/cement/core/foundation.py", line 797, in run
>     return_val = self.controller._dispatch()
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/cement/core/controller.py", line 472, in _dispatch
>     return func()
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/cement/core/controller.py", line 478, in _dispatch
>     return func()
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/core/abstractcontroller.py", line 60, in default
>     self.do_command()
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/controllers/deploy.py", line 92, in do_command
>     staged=self.staged, timeout=self.timeout, source=self.source)
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/operations/deployops.py", line 67, in deploy
>     env_name=env_name)
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/operations/commonops.py", line 123, in wait_for_success_events
>     if _is_success_string(event.message):
>   File "/Users/NetfrontDev/Library/Python/2.7/lib/python/site-packages/ebcli/operations/commonops.py", line 259, in _is_success_string
>     raise ServiceError(message)
> ServiceError: Failed to deploy application.

```
I have set environment variables on mac for aws access key id and secret key also. The environ health on aws has always been sever though.
![eb](https://user-images.githubusercontent.com/39503792/40643130-6909c810-6362-11e8-89b0-f30e1efe3a1e.JPG)

**Comment by benazir0** [comment]
From the log file. I also tried renaming this file beiwe-backend\config\remote_db_env.py.dummy to remote_db_env.py and hardcoded all the values including AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, still it doesn't file the values.

```

> -------------------------------------
> /var/log/eb-commandprocessor.log
> -------------------------------------
>   import config
>   File "/opt/python/bundle/3/app/config/__init__.py", line 75, in <module>
>   raise BadServerConfigurationError("\n" + "\n".join(errors))
>   config.BadServerConfigurationError:
> <<<
>   AWS_SECRET_ACCESS_KEY was not provided with a value.
>    (ElasticBeanstalk::ExternalInvocationError)
> 
> 
> [2018-05-30T02:50:29.162Z] ERROR [9640]  : Command CMD-AppDeploy failed!
> [2018-05-30T02:50:29.162Z] INFO  [9640]  : Command processor returning results: 
> <<<
> [2018-05-30T02:59:12.752Z] DEBUG [10202] : Reading config file: /etc/elasticbeanstalk/.aws-eb-stack.properties
> [2018-05-30T02:59:12.752Z] DEBUG [10202] : Checking if the command processor should execute...
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Checking whether the command is applicable to instance (i-07a033014ec60980c)..
> [2018-05-30T02:59:12.753Z] INFO  [10202] : Command is applicable to this instance (i-07a033014ec60980c)..
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Checking if the received command stage is valid..
> [2018-05-30T02:59:12.753Z] INFO  [10202] : No stage_num in command. Valid stage..
> [2018-05-30T02:59:12.753Z] INFO  [10202] : Received command CMD-AppDeploy: {"execution_data":"{\"leader_election\":\"true\"}","instance_ids":["i-07a033014ec60980c"],"data":"manifest_1527649115136","command_name":"CMD-AppDeploy","api_version":"1.0","resource_name":"AWSEBAutoScalingGroup","request_id":"7b5c1a45-6d78-4126-bcfc-47f5f3844b56"}
> [2018-05-30T02:59:12.753Z] INFO  [10202] : Command processor should execute command.
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Storing current stage..
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Stage_num does not exist. Not saving null stage. Returning..
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Reading config file: /etc/elasticbeanstalk/.aws-eb-stack.properties
> [2018-05-30T02:59:12.753Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_ContainerConfigFileContent||commands..
> [2018-05-30T02:59:12.754Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_API||_Commands..
> [2018-05-30T02:59:12.755Z] INFO  [10202] : Found enabled addons: ["logpublish", "logstreaming"].
> [2018-05-30T02:59:12.756Z] INFO  [10202] : Updating Command definition of addon logpublish.
> [2018-05-30T02:59:12.756Z] INFO  [10202] : Updating Command definition of addon logstreaming.
> [2018-05-30T02:59:12.756Z] DEBUG [10202] : Refreshing metadata...
> [2018-05-30T02:59:13.148Z] DEBUG [10202] : Refreshed environment metadata.
> [2018-05-30T02:59:13.149Z] INFO  [10202] : Recreated directory /opt/elasticbeanstalk/deploy/configuration/.
> [2018-05-30T02:59:13.149Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_AppSourceUrlFileContent||url..
> [2018-05-30T02:59:13.149Z] INFO  [10202] : Created appsource url file at /opt/elasticbeanstalk/deploy/configuration/appsourceurl.
> [2018-05-30T02:59:13.149Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_ContainerConfigFileContent..
> [2018-05-30T02:59:13.151Z] INFO  [10202] : Created container config file at /opt/elasticbeanstalk/deploy/configuration/containerconfiguration.
> [2018-05-30T02:59:13.151Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_ContainerConfigFileContent||commands..
> [2018-05-30T02:59:13.152Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||_API||_Commands..
> [2018-05-30T02:59:13.153Z] INFO  [10202] : Found enabled addons: ["logpublish", "logstreaming"].
> [2018-05-30T02:59:13.154Z] INFO  [10202] : Updating Command definition of addon logpublish.
> [2018-05-30T02:59:13.154Z] INFO  [10202] : Updating Command definition of addon logstreaming.
> [2018-05-30T02:59:13.154Z] DEBUG [10202] : Retrieving metadata for key: AWS::CloudFormation::Init||Infra-WriteApplication2||files..
> [2018-05-30T02:59:13.154Z] DEBUG [10202] : Retrieving metadata for key: AWS::ElasticBeanstalk::Ext||ManifestFileS3Key..
> [2018-05-30T02:59:13.249Z] INFO  [10202] : Loading manifest from bucket 'elasticbeanstalk-ap-southeast-2-888332950069' using computed S3 key 'resources/environments/e-bswddjm5x5/_runtime/versions/manifest_1527649115136'.
> [2018-05-30T02:59:13.404Z] INFO  [10202] : Updated manifest cache: deployment ID 8 and serial 14.
> [2018-05-30T02:59:13.404Z] DEBUG [10202] : Loaded definition of Command CMD-AppDeploy.
> [2018-05-30T02:59:13.404Z] INFO  [10202] : Executing Application update
> [2018-05-30T02:59:13.404Z] INFO  [10202] : Executing command: CMD-AppDeploy...
> [2018-05-30T02:59:13.404Z] INFO  [10202] : Executing command CMD-AppDeploy activities...
> [2018-05-30T02:59:13.404Z] DEBUG [10202] : Setting environment variables..
> [2018-05-30T02:59:13.404Z] INFO  [10202] : Running AddonsBefore for command CMD-AppDeploy...
> [2018-05-30T02:59:13.527Z] DEBUG [10202] : Running stages of Command CMD-AppDeploy from stage 0 to stage 1...
> [2018-05-30T02:59:13.527Z] INFO  [10202] : Running stage 0 of command CMD-AppDeploy...
> [2018-05-30T02:59:13.527Z] INFO  [10202] : Running leader election...
> [2018-05-30T02:59:13.913Z] INFO  [10202] : Instance is Leader.
> [2018-05-30T02:59:13.913Z] DEBUG [10202] : Loaded 5 actions for stage 0.
> [2018-05-30T02:59:13.913Z] INFO  [10202] : Running 1 of 5 actions: DownloadSourceBundle...
> [2018-05-30T02:59:14.240Z] INFO  [10202] : Running 2 of 5 actions: EbExtensionPreBuild...
> [2018-05-30T02:59:15.404Z] INFO  [10202] : Running 3 of 5 actions: AppDeployPreHook...
> [2018-05-30T02:59:17.869Z] INFO  [10202] : Running 4 of 5 actions: EbExtensionPostBuild...
> [2018-05-30T02:59:25.150Z] ERROR [10202] : Command execution failed: Activity failed. (ElasticBeanstalk::ActivityFatalError)
> caused by: Traceback (most recent call last):
>   File "manage.py", line 5, in <module>
>   import config
>   File "/opt/python/bundle/3/app/config/__init__.py", line 75, in <module>
>   raise BadServerConfigurationError("\n" + "\n".join(errors))
>   config.BadServerConfigurationError:
> <<<
>   AWS_SECRET_ACCESS_KEY was not provided with a value.
>    (ElasticBeanstalk::ExternalInvocationError)

```

**Comment by biblicabeebli** [comment]
The variable AWS_SECRET_ACCESS_KEY is not a component of the server, it is a component of the deployment script.  It _was_ the name of an environment variable, but that it was changed quite a while ago.  Are you sure you are on the most recent version of the codebase? You should use the production branch.


The environment variables that Beiwe checks for that will result in the BadServerConfigurationError are the following:
DOMAIN_NAME
FLASK_SECRET_KEY
IS_STAGING
S3_BUCKET
SENTRY_ANDROID_DSN
SENTRY_DATA_PROCESSING_DSN
SENTRY_ELASTIC_BEANSTALK_DSN
SENTRY_JAVASCRIPT_DSN
SYSADMIN_EMAILS
S3_ACCESS_CREDENTIALS_USER
S3_ACCESS_CREDENTIALS_KEY

This list was sourced directly from config/__init__.py


additional info:
This error you are seeing is occurring during one of the management commands, these are defined in the .ebextensions/01.config file.  If you want to you can comment those commands out and they will be skipped. However, if you are missing any of the variables in MANDATORY_VARS in the config/__init__.py file the server code will refuse not start.  That said, if you are having database problems this can be a useful debugging tool.

**Comment by benazir0** [comment]
I added those two variables just to check whether I could get away with the error lol. Sorry, which one are you calling a useful debugging tool? Since we are talking about tools, is it possible to use any debugging tool when we run eb init or deploy command. I'm using PyCharm to debug at the moment.

**Comment by biblicabeebli** [comment]
Its not a tool as much as it is a sanity check.  Lets you deploy updated code but bypass any potentially complex management commend runtime issue.  (management commands include a database schema migration check)

**Comment by benazir0** [comment]
You can close this issue. It's not happening on the current version.
