### ISSUE TITLE
Upgrading to Python3: Application deployment failed

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#77]
Hi,

I've tried to update the environment after updating to python3 but I get an error and the update does not complete.  The error happens after running the command of step 6 in the instructions:

> The conversion.
> 
> This command will take your Python 2 platform and replace it with the python 3 platform. You will see old servers get killed and new ones spun up.
> 
> Be aware that the operation will provide a formatted response but does not block until the process is finished. It will appear to take about 3 seconds, but you should check the status of the cluster and wait for the downtime message of the website to appear again.
> 
> aws elasticbeanstalk update-environment --environment-name "YOUR_CLUSTER_NAME" --region APPROPRIATE_REGION_SHORTNAME --solution-stack-name "THE_SOLUTION_STACK_NAME_IN_QUOTES"

The log from Events:

> 2019-12-30 06:45:42 UTC+0100 | WARN | Environment  health has transitioned from Severe to Degraded. Command failed on 1  out of 2 instances. Configuration update in progress on 1 instance. 0  out of 2 instances completed (running for 7 minutes). ELB health is  failing or not available for 1 out of 2 instances.
> -- | -- | --
> 2019-12-30 06:43:49 UTC+0100 | INFO | Still waiting for the following 1 instances to become healthy: [i-098fa573091049150].
> 2019-12-30 06:40:42 UTC+0100 | INFO | Added instance [i-098fa573091049150] to your environment.
> 2019-12-30 06:40:00 UTC+0100 | INFO | Auto  Scaling group update progress: New instance(s) added to autoscaling  group - Waiting on 1 resource signal(s) with a timeout of PT30M.
> 2019-12-30 06:39:19 UTC+0100 | INFO | Auto Scaling group update progress: Temporarily setting autoscaling group MinSize and DesiredCapacity to 2.
> 2019-12-30 06:39:18 UTC+0100 | INFO | Auto  Scaling group update progress: Rolling update initiated. Terminating 1  obsolete instance(s) in batches of 1, while keeping at least 1  instance(s) in service. Waiting on resource signals with a timeout of  PT30M when new instances are added to the autoscaling group.
> 2019-12-30 06:39:03 UTC+0100 | INFO | Created Auto Scaling launch configuration named: awseb-e-xbsugqhq4j-stack-AWSEBAutoScalingLaunchConfiguration-161RCIUEY1S6B
> 2019-12-30 06:38:41 UTC+0100 | INFO | Environment update is starting.
> 2019-12-30 06:31:42 UTC+0100 | WARN | Environment  health has transitioned from Ok to Severe. 47.1 % of the requests to  the ELB are failing with HTTP 5xx. Insufficient request rate (8.5  requests/min) to determine application health (4 minutes ago). ELB  health is failing or not available for all instances.
> 2019-12-30 06:24:42 UTC+0100 | INFO | Environment health has transitioned from Warning to Ok.
> 2019-12-30 06:23:42 UTC+0100 | WARN | Environment health has transitioned from Ok to Warning. 100.0 % of the requests are failing with HTTP 5xx.
> 2019-12-30 06:21:42 UTC+0100 | INFO | Environment health has transitioned from Severe to Ok.
> 2019-12-30 06:01:43 UTC+0100 | WARN | Environment  health has transitioned from Ok to Severe. 50.0 % of the requests to  the ELB are failing with HTTP 5xx. Insufficient request rate (4.0  requests/min) to determine application health (4 minutes ago). ELB  health is failing or not available for all instances.

And this is the log that I can find in the Health section of the application in ElasticBeanstalk:

> Checking instance health (running for 2 minutes).
> Application deployment failed at 2019-12-30T05:46:43Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/enact/01flip.py failed.
> 
> httpd: ERROR (not running)
> httpd: ERROR (abnormal termination)
> apache failed to start... killing all existing httpd processes and trying again
> httpd: no process found
> Semaphores owned by apache:
> Deleting apache semaphores:
> httpd: ERROR (already started)
> Traceback (most recent call last):
> File "/opt/elasticbeanstalk/hooks/appdeploy/enact/01flip.py", line 42, in <module>
> main()
> File "/opt/elasticbeanstalk/hooks/appdeploy/enact/01flip.py", line 36, in main
> config.restart_apache()
> File "/opt/elasticbeanstalk/hooks/config.py", line 251, in restart_apache
> apache_cmd('restart', should_be_running=True)
> File "/opt/elasticbeanstalk/hooks/config.py", line 258, in apache_cmd
> ensure_apache_is_running()
> File "/opt/elasticbeanstalk/hooks/config.py", line 280, in ensure_apache_is_running
> raise PythonHooksError("Apache is not running, but it's supposed to be.")
> config.PythonHooksError: Apache is not running, but it's supposed to be.
> Instance ELB health state has been "OutOfService" for 7 minutes: Instance has failed at least the UnhealthyThreshold number of health checks consecutively.

**Comment by usanchez** [comment]
This issue was very specific to my case. To deal with all the SSL stuff I  used and installed the mod_ssl in the original platform. So, to make this new version work I had to install this module again. To force this installation I modified the contents of the `01.config` file in the `.ebextensions` folder:
```

packages:
  yum:
    gcc: []
    postgresql96-devel: []
    mod24_ssl: []

commands:
  01_setup_swap:
    ignoreErrors: true
    command: fallocate -l 5G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && swapon -s
  02_yum_installs_could_not_get_packages_to_work:
    command: yum -y install htop ack python-devel postgresql-devel git ec2-metadata
  03_pagespeed_1_download:
      command: "rpm -q mod-pagespeed-stable || wget https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_x86_64.rpm"
  03_pagespeed_2_install:
      command: "rpm -q mod-pagespeed-stable || rpm -U mod-pagespeed-*.rpm"
  04_force_ec2_metadata:
      ignoreErrors: true
      command: "ln -s /opt/aws/bin/ec2-metadata /usr/local/bin/ec2-metadata"

container_commands:
  01_add_global_wsgi_application_group:
    command: if ! grep -q 'WSGIApplicationGroup %{GLOBAL}' ../wsgi.conf ; then echo 'WSGIApplicationGroup %{GLOBAL}' >> ../wsgi.conf; fi;
  02_update_pip:
    command: pip install --upgrade pip
  03_install_requirements:
    command: pip install --requirement requirements.txt
  04_migrate:
    leader_only: true
    command: python manage.py migrate
  05_setup_profile:
    command: mv ./cluster_management/pushed_files/eb_profile.sh /home/ec2-user/.bashrc; chmod 644 /home/ec2-user/.bashrc; chown ec2-user /home/ec2-user/.bashrc; chgrp ec2-user /home/ec2-user/.bashrc
  06_setup_reasonable_inputrc:
    command: mv ./cluster_management/pushed_files/.inputrc /home/ec2-user/.inputrc; chmod 664 /home/ec2-user/.inputrc; chown ec2-user /home/ec2-user/.inputrc; chgrp ec2-user /home/ec2-user/.inputrc

option_settings:
  aws:elasticbeanstalk:container:python:staticfiles:
    /static/: frontend/static/
  aws:elasticbeanstalk:container:python:
    WSGIPath: wsgi.py
# DO NOT ENABLE THIS.  Elastic beanstalk's memory for this parameter is really inconsistent.  You should set this manually
# in the AWS Console.
#    NumProcesses: 2
#    NumThreads: 20


# uncomment this section to force SSL connections
files:
  "/etc/httpd/conf.d/ssl_rewrite.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
        LoadModule ssl_module modules/mod_ssl.so
        RewriteEngine On
        <If "-n '%{HTTP:X-Forwarded-Proto}' && %{HTTP:X-Forwarded-Proto} != 'https'">
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
        </If>

        # disable trace and track requests
        RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK) [NC]
        RewriteRule .* - [F]

        #hsts - set strict transport security for a year from first access
        Header set Strict-Transport-Security "max-age=31536000"

```

After making these changes and giving the upgrade another try solved the issue.
