### ISSUE TITLE
Upgrading to Python3: error launching manager

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#78]
So I successfully upgraded the code and the platform to Python3 and what I have left to do is launching the new manager. 

When I run the code the first error that I got was `No module names 'fabric`. I looked for it in the code and this module is mentioned in the file `launch_requirements.txt` inside the `cluster_management` folder. Running the command `pip3 install -r launch_requirements.txt` from the `cluster_management` folder solved this first issue.

However, after this, the script throws another error:

> FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/PycharmProjects/beiwe-backend/cluster_management/general_configuration/aws_credentials.json'

So my guess is that after upgrading the platform, the configuration files and the initial installation of the requirements have not been preserved, so it's something that has to be done again.

I'll update as I progress with the execution of the `launch_script.py`.

**Comment by usanchez** [comment]
I had to perform the steps 6, 7, and 8 to create the configuration files of the folders `general_configuration `and `environment_configuration`, BUT without creating a new environment. I created the files manually and added the required stuff from a backup that I  had of these configuration files.

After that, I rerun the script and found the following error:

```
WARNING cluster-management: No manager found.
INFO cluster-management: Using AMI 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20191113-3b73ef49-208f-47e1-8a6e-4ae768d8a333-ami-00a208c7cdba991ea.4'
ERROR cluster-management: An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3iplms73etrdhxdepv72l6ywj
```

So, I went to that page, I subscribed to that AMI and then accepted the terms. I rerun the create manager command and got the following error:

```
INFO cluster-management: Using AMI 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20191113-3b73ef49-208f-47e1-8a6e-4ae768d8a333-ami-00a208c7cdba991ea.4'
INFO cluster-management: Waiting for server i-053afdf287ac47f94 to show up...
INFO cluster-management: Waiting until server i-053afdf287ac47f94 is up and running (this may take a minute) ...
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Timed out trying to connect to 63.33.196.159 (tried 1 time)"
Retrying with attempt 1.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 2.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 3.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 4.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 5.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 6.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 7.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 8.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 9.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 10.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 63.33.196.159 on port 22: No such file or directory (tried 1 time)"
Retrying with attempt 11.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR paramiko.transport: Exception: Error reading SSH protocol banner
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR paramiko.transport:     buf = self.packetizer.readline(timeout)
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
ERROR paramiko.transport:     buf += self._read_timeout(timeout)
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR paramiko.transport:     raise EOFError()
ERROR paramiko.transport: EOFError
ERROR paramiko.transport: 
ERROR paramiko.transport: During handling of the above exception, another exception occurred:
ERROR paramiko.transport: 
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
ERROR paramiko.transport:     self._check_banner()
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
ERROR paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERROR paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR paramiko.transport: 
ERROR cluster-management: Encountered error of type NetworkError with error message "Error reading SSH protocol banner"
Retrying with attempt 12.
[63.33.196.159] run: # waiting for ssh to be connectable...
ERROR paramiko.transport: Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR paramiko.transport:     buf = self.packetizer.readline(timeout)
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
ERROR paramiko.transport:     buf += self._read_timeout(timeout)
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 607, in _read_timeout
ERROR paramiko.transport:     x = self.__socket.recv(128)
ERROR paramiko.transport: ConnectionResetError: [Errno 104] Connection reset by peer
ERROR paramiko.transport: 
ERROR paramiko.transport: During handling of the above exception, another exception occurred:
ERROR paramiko.transport: 
ERROR paramiko.transport: Traceback (most recent call last):
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
ERROR paramiko.transport:     self._check_banner()
ERROR paramiko.transport:   File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
ERROR paramiko.transport:     "Error reading SSH protocol banner" + str(e)
ERROR paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR paramiko.transport: 

Fatal error: Needed to prompt for a connection or sudo password (host: 63.33.196.159), but abort-on-prompts was set to True

Aborting.
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 478, in connect
    client.connect(**kwargs)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launch_script.py", line 543, in <module>
    do_create_manager()
  File "launch_script.py", line 382, in do_create_manager
    configure_fabric(name, public_ip)
  File "launch_script.py", line 74, in configure_fabric
    retry(run, "# waiting for ssh to be connectable...")
  File "/home/ubuntu/PycharmProjects/beiwe-backend/cluster_management/deployment_helpers/general_utils.py", line 48, in retry
    return func(*args, **kwargs)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/operations.py", line 1095, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/state.py", line 416, in _open_session
    transport = connections[env.host_string].get_transport()
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 156, in __getitem__
    self.connect(key)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 148, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 566, in connect
    password = prompt_for_password(text)
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/network.py", line 643, in prompt_for_password
    handle_prompt_abort("a connection or sudo password")
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/utils.py", line 181, in handle_prompt_abort
    abort(reason % "abort-on-prompts was set to True")
  File "/home/ubuntu/PycharmProjects/beiwe-backend/venv/lib/python3.6/site-packages/fabric/utils.py", line 55, in abort
    raise env.abort_exception(msg)
__main__.FabricExecutionError: Needed to prompt for a connection or sudo password (host: 63.33.196.159), but abort-on-prompts was set to True
```

**Comment by usanchez** [comment]
So, I think that the cause of this new problem is that I forgot to add the SSH key to the `~/.ssh/` path. But, after terminating the server manager and re-running the script, I got a new error that says:

```
ERROR cluster-management: Encountered error of type NetworkError with error message "Low level socket error connecting to host 34.242.254.109 on port 22: Permission denied (tried 1 time)"
Retrying with attempt 23.
```

I'll re-check if I mess anything with the configuration of the SSH.

**Comment by biblicabeebli** [comment]
as long as you got to themes of the deploy process you should be good.

(Credential management could be.... improved. Or at least consolidated better...)

**Comment by biblicabeebli** [comment]
Can we close this thread?

**Comment by usanchez** [comment]
Sure!
